/**
 * The per-game report.
 *
 * Assembled entirely from the rep records, with no hand-written prose: the
 * findings at the bottom are generated by rules that read the same numbers shown
 * above them, and each one carries the figure that triggered it. If a finding
 * cannot name a number it does not get written.
 */

import { metric, type MetricId } from '../domain/metrics';
import type { GameSummary, ThrowRecord } from '../domain/types';
import { aggregate, isChaos, isPressured, isThrow } from './aggregate';
import { detectFlags, type RiskFlag } from './baseline';
import {
  composure,
  fatigueSplit,
  pressureSplits,
  situationalByState,
  situationalScore,
  successRate,
  type Composure,
  type Split,
} from './splits';

export interface ReportHeadline {
  id: MetricId;
  value: number | null;
  /** Same metric across the rest of the season, for context. */
  seasonValue: number | null;
}

export interface ReportFinding {
  severity: 'positive' | 'neutral' | 'attention';
  text: string;
}

export interface GameReport {
  game: GameSummary;
  dropbacks: number;
  throws: number;
  headlines: ReportHeadline[];
  pressure: Split[];
  fatigue: Split[];
  composure: Composure;
  situational: { score: number | null; byState: { state: string; score: number | null; reps: number }[] };
  cognitiveLoad: { meanLoad: number | null; highLoadOnTarget: number | null; lowLoadOnTarget: number | null; highLoadReps: number };
  chaosReps: number;
  flags: RiskFlag[];
  findings: ReportFinding[];
}

const HEADLINE_METRICS: MetricId[] = [
  'oodaLoop',
  'decisionLatency',
  'timeToRelease',
  'onTargetRate',
  'releaseConsistency',
  'anticipatoryRate',
  'sequenceOrder',
  'epaPerDropback',
];

export function buildGameReport(
  game: GameSummary,
  gameRecords: readonly ThrowRecord[],
  seasonRecords: readonly ThrowRecord[],
): GameReport {
  const rest = seasonRecords.filter((r) => r.context.gameId !== game.id);
  const highLoad = gameRecords.filter((r) => r.cognition.workingMemoryLoad >= 5);
  const lowLoad = gameRecords.filter((r) => r.cognition.workingMemoryLoad <= 3);

  const report: GameReport = {
    game,
    dropbacks: gameRecords.length,
    throws: gameRecords.filter(isThrow).length,
    headlines: HEADLINE_METRICS.map((id) => ({
      id,
      value: aggregate(gameRecords, id),
      seasonValue: aggregate(rest, id),
    })),
    pressure: pressureSplits(gameRecords),
    fatigue: fatigueSplit(gameRecords),
    composure: composure(gameRecords),
    situational: { score: situationalScore(gameRecords), byState: situationalByState(gameRecords) },
    cognitiveLoad: {
      meanLoad: aggregate(gameRecords, 'workingMemoryLoad'),
      highLoadOnTarget: highLoad.length >= 6 ? aggregate(highLoad, 'onTargetRate') : null,
      lowLoadOnTarget: lowLoad.length >= 6 ? aggregate(lowLoad, 'onTargetRate') : null,
      highLoadReps: highLoad.length,
    },
    chaosReps: gameRecords.filter(isChaos).length,
    // A single game is never enough reps to flag against; the game report shows
    // what the season-to-date engine found, so the report is honest about the
    // window the finding came from.
    flags: detectFlags(gameRecords, rest),
    findings: [],
  };

  report.findings = deriveFindings(report, gameRecords, rest);
  return report;
}

function fmt(id: MetricId, value: number | null): string {
  if (value === null) return '—';
  const def = metric(id);
  return `${value.toFixed(def.precision)}${def.unit ? ` ${def.unit}` : ''}`;
}

/**
 * The findings block.
 *
 * Every rule below compares this game against the rest of the season for the
 * same athlete, requires a rep floor, and states the two numbers it compared.
 * The result reads like a staff note because it is built the way a staff note is
 * built, not because the wording was written to sound like one.
 */
function deriveFindings(
  report: GameReport,
  gameRecords: readonly ThrowRecord[],
  rest: readonly ThrowRecord[],
): ReportFinding[] {
  const findings: ReportFinding[] = [];

  const loop = aggregate(gameRecords, 'oodaLoop');
  const loopSeason = aggregate(rest, 'oodaLoop');
  if (loop !== null && loopSeason !== null && gameRecords.length >= 20) {
    const delta = loop - loopSeason;
    if (Math.abs(delta) >= 90) {
      findings.push({
        severity: delta < 0 ? 'positive' : 'attention',
        text: `OODA loop ran ${Math.abs(Math.round(delta))} ms ${delta < 0 ? 'shorter' : 'longer'} than the season median (${Math.round(loop)} ms vs ${Math.round(loopSeason)} ms). ${dominantSpan(gameRecords, rest)}`,
      });
    }
  }

  const onTargetSplit = report.pressure.find((s) => s.metric === 'onTargetRate');
  if (onTargetSplit?.reliable && onTargetSplit.delta !== null) {
    findings.push({
      severity: onTargetSplit.delta > -12 ? 'positive' : 'attention',
      text: `Pressure cost ${Math.abs(onTargetSplit.delta).toFixed(1)} points of on-target rate (${(onTargetSplit.a ?? 0).toFixed(1)}% pressured on ${onTargetSplit.nA} reps vs ${(onTargetSplit.b ?? 0).toFixed(1)}% clean on ${onTargetSplit.nB}).`,
    });
  }

  const { highLoadOnTarget, lowLoadOnTarget, highLoadReps } = report.cognitiveLoad;
  if (highLoadOnTarget !== null && lowLoadOnTarget !== null) {
    const gap = lowLoadOnTarget - highLoadOnTarget;
    findings.push({
      severity: gap >= 14 ? 'attention' : 'neutral',
      text: `Calls carrying five or more live variables (${highLoadReps} reps) returned ${highLoadOnTarget.toFixed(1)}% on target against ${lowLoadOnTarget.toFixed(1)}% on three or fewer — a ${gap.toFixed(1)}-point load penalty.`,
    });
  }

  const velocityFatigue = report.fatigue.find((s) => s.metric === 'velocity');
  if (velocityFatigue?.reliable && velocityFatigue.delta !== null && Math.abs(velocityFatigue.delta) >= 0.8) {
    findings.push({
      severity: velocityFatigue.delta < 0 ? 'attention' : 'neutral',
      text: `Fourth-quarter ball speed ${velocityFatigue.delta < 0 ? 'fell' : 'rose'} ${Math.abs(velocityFatigue.delta).toFixed(1)} mph against the first three quarters (${(velocityFatigue.a ?? 0).toFixed(1)} vs ${(velocityFatigue.b ?? 0).toFixed(1)} mph, n = ${velocityFatigue.nA}/${velocityFatigue.nB}).`,
    });
  }

  const scatter = aggregate(gameRecords, 'releaseConsistency');
  const scatterSeason = aggregate(rest, 'releaseConsistency');
  if (scatter !== null && scatterSeason !== null && Math.abs(scatter - scatterSeason) >= 0.35) {
    findings.push({
      severity: scatter > scatterSeason ? 'attention' : 'positive',
      text: `Release point ${scatter > scatterSeason ? 'scattered wider' : 'held tighter'} than the season baseline (${fmt('releaseConsistency', scatter)} vs ${fmt('releaseConsistency', scatterSeason)} RMS).`,
    });
  }

  const sequence = aggregate(gameRecords, 'sequenceOrder');
  if (sequence !== null && sequence < 82) {
    findings.push({
      severity: 'attention',
      text: `Kinetic chain sequenced proximal-to-distal on only ${sequence.toFixed(0)}% of throws; out-of-order reps move load off the trunk and onto the arm.`,
    });
  }

  if (report.composure.reliable) {
    findings.push({
      severity: report.composure.score >= 70 ? 'positive' : report.composure.score >= 55 ? 'neutral' : 'attention',
      text: `Composure ${report.composure.score}/100 across ${report.composure.pressuredReps} pressured and ${report.composure.cleanReps} clean dropbacks — ${report.composure.components.map((c) => `${c.label} ${c.delta > 0 ? '+' : ''}${c.delta.toFixed(1)} ${c.unit}`).join(', ')}.`,
    });
  }

  for (const flag of report.flags.slice(0, 2)) {
    const def = metric(flag.metric);
    findings.push({
      severity: 'attention',
      text: `${def.label} sat ${Math.abs(flag.z).toFixed(1)} robust SD from this athlete's own season distribution (${flag.recentMedian.toFixed(def.precision)} vs ${flag.baselineMedian.toFixed(def.precision)} ${def.unit}) — ${flag.note}.`,
    });
  }

  return findings;
}

/** Which OODA span moved most between this game and the rest of the season. */
function dominantSpan(gameRecords: readonly ThrowRecord[], rest: readonly ThrowRecord[]): string {
  const spans: MetricId[] = ['oodaObserve', 'oodaOrient', 'oodaDecide', 'oodaAct'];
  let bestId: MetricId | null = null;
  let bestDelta = 0;
  for (const id of spans) {
    const a = aggregate(gameRecords, id);
    const b = aggregate(rest, id);
    if (a === null || b === null) continue;
    if (Math.abs(a - b) > Math.abs(bestDelta)) {
      bestDelta = a - b;
      bestId = id;
    }
  }
  if (!bestId) return '';
  return `${metric(bestId).label} carried the change at ${bestDelta > 0 ? '+' : ''}${Math.round(bestDelta)} ms.`;
}

/** Pressure-only view of a game, for the "under duress" panel. */
export function duressRecords(records: readonly ThrowRecord[]): ThrowRecord[] {
  return records.filter((r) => isPressured(r) || isChaos(r));
}

/** Game-level success rate, kept here so the report and the trends view agree. */
export function gameSuccessRate(records: readonly ThrowRecord[]): number | null {
  return successRate(records);
}
